site_name: Hector Tiling

site_author: Sam Vaughan

repo_url: https://github.com/samvaughan/hector-tiling/
repo_name: Hector Tiling

nav:
  - Home: 'index.md'
  - A simple walkthrough: 'walkthrough.md'
  - Issues for the future: 'issues.md'
  - Other Hector Documentation: 
    - Observing Pipeline: 'https://samvaughan.info/hector-observing/'
    - Input Catalogue : 'https://samvaughan.info/hector-input-catalogues/'

theme: 
  name: material
  palette:
    primary: black
  logo: img/favicon.png
  favicon: img/favicon.png


  
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js